SmartLinkClient/SmartLinkClient/SmartLinkClient/Models/ErrorViewModel.cs
namespace SmartLinkClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Models/LinkViewModel.cs
namespace SmartLinkClient.Models
{
    public class LinkViewModel
    {
        public string Url { get; set; }
        public string? Summary { get; set; }
        public string Title { get; set; }
    }
}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Models/VpnResponse.cs
using System.Text.Json.Serialization;

namespace SmartLinkClient.Models
{
    public class VpnResponse
    {
        [JsonPropertyName("security")]
       public SecurityInfo Security { get; set; }
    }

    public class SecurityInfo
    {
        [JsonPropertyName("vpn")]
        public bool Vpn { get; set; }
    }


}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;


namespace SmartLinkClient.Controllers
{
    public class ErrorController : Controller
    {

        [HttpGet]
        public IActionResult Index(int statusCode)
        {
            if(statusCode == 401)
            {
                return View("Unathorized");
            }
            return NotFound();
        }

        public IActionResult ErrorVpn()
        {
            return View();
        }

    }
}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Policy;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SmartLinkClient.Interfaces;
using SmartLinkClient.Models;
using Google.Apis.Auth.AspNetCore3;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Google.Apis.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;


namespace SmartLinkClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IVpnDetectorService _vpnDetectorService;

        public HomeController(ILogger<HomeController> logger, IVpnDetectorService vpnDetectorService)
        {
            _logger = logger;
            _vpnDetectorService = vpnDetectorService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
           // if (await _vpnDetectorService.IsUsingVpn())
             //   return RedirectToAction("ErrorVpn", "Error");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

      
   

    }
}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Controllers/SummaryController.cs
using Microsoft.AspNetCore.Mvc;


namespace SmartLinkClient.Controllers
{
    public class SummaryController : Controller
    {

        [HttpGet]
        public IActionResult MySummaries()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Index(string id)
        {
            ViewBag.Id = id;
            return View();
        }

    }
}

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL Summarizer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/microsoft-signalr/signalr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Login.js?v=2"></script>
    <script src="~/js/Authenticate.js?v=2"></script>
    <script src="~/js/Register.js?v=2"></script>
    <script src="~/js/signalr.js?v=2"></script>
    <link rel="stylesheet" href="~/css/index.css?v=1" />
</head>

<body>
    <div class="main-container">
        <partial name="_NavbarPartial"></partial>
        <!-- Login Modal -->
        <div id="login-modal" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Login</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                               <div class="mb-3">
                                <label for="email" class="col-form-label">Email</label>
                                <input type="email" class="form-control" id="email" autocomplete="email">
                            </div>
                            <div class="mb-3">
                                <label for="password" class="col-form-label">Password</label>
                                <input type="password" class="form-control" id="password"
                                       autocomplete="current-password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button id="modalLoginBtn" type="button" class="btn btn-primary">Login</button>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- Register Modal -->
        <div id="register-modal" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Register</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="mb-3">
                                <label for="email" class="col-form-label">Email</label>
                                <input type="email" class="form-control" id="register-email" autocomplete="email">
                            </div>
                            <div class="mb-3">
                                <label for="username" class="col-form-label">Username</label>
                                <input type="text" class="form-control" id="register-username" autocomplete="username">
                            </div>
                            <div class="mb-3">
                                <label for="password" class="col-form-label">Password</label>
                                <input type="password" class="form-control" id="register-password"
                                       autocomplete="current-password">
                            </div>
                            <div class="mb-3">
                                <label for="password" class="col-form-label">Repeat Password</label>
                                <input type="password" class="form-control" id="password-repeat"
                                       autocomplete="current-password">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button id="modalRegisterBtn" type="button" class="btn btn-primary">Register</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <span id="loader" class="loader"></span>
    <div id=loader-overlay class="loader-overlay"></div>
    <div class="input-section">
        <input id="url-input" type="text" class="input-field" placeholder="Enter URL here" required>
        <button id="urlSubmitBtn" class="submit-button" type="button">Submit</button>
    </div>

<div id="summary" class="summary-container">
    <!-- Summary content will appear here -->
</div>
<p>Last 5 queries</p>
<ul id ="list-item" class="list-group"></ul>
    <partial name="~/Views/Shared/_ToastPartial.cshtml" />
    <footer class="footer">
        <a target="_blank "href="https://www.github.com/enisertdev"><div class="footer-content">© Enisertdev </div></a>
    </footer>
    <script>
        let urlSubmit = document.getElementById("urlSubmitBtn");
        let summaryContainer = document.getElementById("summary");
        let blurEffect = document.getElementById("loader-overlay");
        let loader = document.getElementById("loader");
        let loginBtn = document.getElementById("loginBtn");
        let logoutBtn = document.getElementById("logoutBtn");
        let loginModal = new bootstrap.Modal(document.getElementById("login-modal"));
        let loginBtnModal = document.getElementById("modalLoginBtn");
        const toastEl = document.getElementById("liveToast");
        const toast = new bootstrap.Toast(toastEl);
        const summariesBtn = document.getElementById("mySummariesBtn");
        const registerBtn = document.getElementById("registerBtn");
        const registerModal = new bootstrap.Modal(document.getElementById("register-modal"));
        const registerModalBtn = document.getElementById("modalRegisterBtn");
        const linkList = document.getElementById("list-item");

        const loginManager = new LoginManager(loginBtn, logoutBtn, loginModal, loginBtnModal,);
        loginManager.init();

        const authManager = new AuthenticateManager();
        authManager.init();

        const registerManager = new RegisterManager(registerBtn, registerModal, registerModalBtn);
        registerManager.init();

        window.addEventListener("DOMContentLoaded", async () => {
            const token = localStorage.getItem("jwt");
            const email = localStorage.getItem("email");
            if (!email || !token) {
                toggleLoginStyles(false);
                return;
            }
           // last5Queries();
            try {
                const isValid = await authManager.isValidJwt();
                toggleLoginStyles(isValid);
            }
            catch (error) {
                console.error("JWT doğrulama hatası:", error);
                showToast("ERROR", "Sunucu hatası.");
            }
        });


        urlSubmit.addEventListener("click", () => {
            let url = document.getElementById("url-input").value;
            if (url.trim() == "") {
                showToast("ERROR", "URL is required.");
                return;
            }
            if (!checkValidUrl(url)) {
                showToast("ERROR", "URL is invalid.");
                return;
            }
            getSummary(url);
        });

        summariesBtn.addEventListener("click", () => {
            window.location.href = "/Summary/MySummaries";
        });

        function showToast(messageType, message) {
            const toastMessage = document.getElementById("toast-message");
            const msgType = document.getElementById("message-type");
            toastMessage.textContent = message;
            msgType.textContent = messageType;
            toastEl.classList.remove("success-toast", "error-toast", "warning-toast");
            if (messageType === "SUCCESS") {
                toastEl.classList.add("success-toast");
            } else if (messageType === "ERROR") {
                toastEl.classList.add("error-toast");
            } else if (messageType === "WARNING") {
                toastEl.classList.add("warning-toast");
            }
            toast.show();
            setTimeout(() => {
                toast.hide();
            }, 10000);
        }

        function checkValidUrl(url) {
            try {
                new URL(url);
                return true;
            } catch (e) {
                return false;
            }
        }

        function toggleLoginStyles(isLoginValid) {
            if (isLoginValid) {
                logoutBtn.style.display = "block";
                loginBtn.style.display = "none";
                summariesBtn.style.display = "block";
                registerBtn.style.display = "none";

            }
            else {
                logoutBtn.style.display = "none";
                loginBtn.style.display = "block";
                summariesBtn.style.display = "none";
                registerBtn.style.display = "block";

            }
        }


        function activateLoader() {
            blurEffect.style.display = "block";
            loader.style.display = "block";
        }
        function deactivateLoader() {
            blurEffect.style.display = "none";
            loader.style.display = "none";
        }

        async function getSummary(url) {
            activateLoader();
            try {
                const response = await fetch("https://smartlinkapi.imaginewebsite.com.tr/api/link", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "Authorization": `Bearer ${localStorage.getItem("jwt")}`
                    },
                    body: JSON.stringify({ url: url }),
                });
                if (response.status == 401 || response.status == 403) {
                    showToast("ERROR", "Invalid token,please login.");
                    return;
                }
                if (!response.ok) {
                    throw new Error(`Response Status: ${response.status}`);
                }
                const json = await response.json();
                summaryContainer.innerText = json.summary;
            }
            catch (error) {
                console.log(error.message);
            }
            finally {
                deactivateLoader();
            }
        }

        async function last5Queries(){
            linkList.innerHTML = '';
            const response = await fetch("https://smartlinkapi.imaginewebsite.com.tr/api/link/last5");
            const json = await response.json();
            if(!response.ok)
            {
                console.log(json.status);
            }
            json.title.forEach(link =>{
                let li = document.createElement("li");
                li.classList.add("list-group-item");
                li.textContent = link.title;
                linkList.appendChild(li);
                li.style.cursor = "pointer";
                li.addEventListener("click", () => {
                    const baseUrl = `@Url.Action("Index","Summary")`;
                    window.location.href = `${baseUrl}?id=${link.id}`;
                })
            });

        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartLinkClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartLinkClient.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SmartLinkClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SmartLinkClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Shared/_NavbarPartial.cshtml
<nav class="navbar">
    <div class="left">
        <button id="mySummariesBtn" class="login-button">My Summaries</button>
    </div>
    <div class="right">
        <button id="loginBtn" class="login-button">Login</button>
        <button id="registerBtn" class="login-button">Register</button>
        <button id="logoutBtn" class="logout-button">Logout</button>
    </div>
</nav>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Shared/_ToastPartial.cshtml
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <strong class="me-auto" id="message-type">Bootstrap</strong>
      <small>Just now</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body" id="toast-message">
      Hello, world! This is a toast message.
    </div>
  </div>
</div>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Summary/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            display: flex;
            justify-content: space-between;
            padding: 15px;
            background-color: #f5f5f5;
        }

        .title {
            font-weight: bold;
        }

        .share-button {
            background-color: #0066cc;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
        }

        .summary {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            text-align: center;
        }


    </style>
</head>
<body>
    <header>
        <div class="title" id="link-title">Title</div>
        <div class="container">
            <button id="go-backBtn">Go back</button>
            <button id="copyBtn" class="copy-btn">
                Copy link
            </button>
        </div>
    </header>
    <div class="summary">
        <h2>Summary</h2>
        <p id="summary"></p>
    </div>
    <script>

        const goBackBtn = document.getElementById("go-backBtn");
        goBackBtn.addEventListener("click", () =>{
            window.location.href = "@Url.Action("MySummaries","Summary")";
        });




        async function fetchSummary(){

        let linkId = '@ViewBag.Id';

        const response = await fetch(`https://smartlinkapi.imaginewebsite.com.tr/api/link/${linkId}`);

        const json = await response.json();

        if(!response.ok)
            console.log(json.message);

        const summary = document.getElementById("summary");
        const title = document.getElementById("link-title");

        summary.innerText = json.summary;
        title.innerText = json.title;
        }

        fetchSummary();


       const copyButton = document.getElementById("copyBtn");

        const addToClipboard = async (link) => {
            await navigator.clipboard.writeText(link);
        };


         copyButton.addEventListener("click", async () => {
            let currentLocation = window.location;
            await addToClipboard(currentLocation);
        });


    </script>
</body>
</html>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Summary/MySummaries.cshtml
@{
    Layout = null;
}

<html>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="~/css/summary.css"/>
<body>
<button id="homeBtn">Home</button>
<ul class="list-group" id="summaries">
</ul>
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Modal title</h5>
            </div>
            <div class="modal-body" id="modal-content">
                ...
            </div>
            <div class="modal-footer">
                <button id="show-fullpageBtn" type="button" class="btn btn-primary"
                        data-dismiss="modal">
                    Show in full page
                </button>
                <button id="close-modalBtn" type="button" class="btn btn-secondary"
                        data-dismiss="modal">
                    Close
                </button>
                <button id="delete-linkBtn" type="button" class="btn btn-danger"
                        data-dismiss="modal">
                    Delete
                </button>
            </div>
        </div>
    </div>
</div>

<script>
        let currentId;
        window.addEventListener("DOMContentLoaded", async () => {
            const response = await fetch(`https://smartlinkapi.imaginewebsite.com.tr/api/link/getlinks`, {
                headers: {
                    "Authorization": `Bearer ${localStorage.getItem("jwt")}`
                }
            });

            if (!response.ok) {
                window.location.href = "/error?statusCode=401";
            }

            const json = await response.json();
            const summaryList = document.getElementById("summaries");

            json.url.forEach(link => {
                let li = document.createElement("li");
                li.classList.add("list-group-item");
                li.textContent = link.title;
                li.dataset.id = link.id;
                summaryList.appendChild(li);
                li.style.cursor = "pointer";
                li.addEventListener("click", () => {
                    showModal(link.title, link.summary, link.id);
                })
            });
        });

        const summaryModal = new bootstrap.Modal(document.getElementById("exampleModalLong"));
        const modalBtn = document.getElementById("launch-modal");
        const closeModalBtn = document.getElementById("close-modalBtn");
        const deleteLinkBtn = document.getElementById("delete-linkBtn");
        const homeBtn = document.getElementById("homeBtn");
        const showFullPageBtn = document.getElementById("show-fullpageBtn");

        deleteLinkBtn.addEventListener("click", async () =>{
            await deleteLink(currentId);
        });

        closeModalBtn.addEventListener("click", () => {
            summaryModal.hide();
        })
        
        homeBtn.addEventListener("click", () =>{
            window.location.href ="/home";
        });

        showFullPageBtn.addEventListener("click", () =>{
            const baseUrl = '@Url.Action("Index","Summary")';
            window.location.href = `${baseUrl}?id=${currentId}`;
        });



        function showModal(title, content,id) {
            const modalBody = document.getElementById("modal-content");
            const modalTitle = document.getElementById("modalTitle");
            modalBody.innerText = content;
            modalTitle.innerText = title;
            currentId = id;
            summaryModal.show();
        }

        async function deleteLink(id)
        {
            const response = await fetch(`https://smartlinkapi.imaginewebsite.com.tr/api/link/delete/${id}`,
            {
                method: "DELETE",
                headers:{
                    "Authorization": `Bearer ${localStorage.getItem("jwt")}`
                }
            });
            if(!response.ok)
            {
                console.log(response.status);
            }
            document.querySelector(`li[data-id="${id}"]`).remove();
            summaryModal.hide();
            console.log(response.status);

        }

    </script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

SmartLinkClient/SmartLinkClient/SmartLinkClient/Views/Summary/Summary.cshtml
<script>
    let linkId = @ViewBag.Id;
    const response = await fetch(`https://smartlinkapi.imaginewebsite.com.tr/api/link/id${linkId}`);
    const json = response.json();
    if(!response.ok)
        console.log(json.message);
    const summaryEl = document.createElement("h1");
    summaryEl.innerText = json.summary;
</script>